---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci(deps)
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"
      osv-scanner:
        patterns:
          - "google/osv-scanner-action*"
