---
name: Feature request
description: Suggest a new feature for this project.
title: "[Feature]: "
labels:
  - enhancement
assignees:
  - thomasleplus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Feature description
      description: |
        A clear and concise description of what the desired feature is and why it would be useful.
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        If you think that there are some implementation details to be taken into consideration, or anything that is not obvious from the previous description, please specify it here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: markdown
    validations:
      required: false

