---
name: "Dependency Review"
on: [pull_request]

permissions: {}

jobs:
  dependency-review:
    permissions:
      # Required to read the code
      contents: read
      # Required to write summary to pull-request
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Dependency Review"
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: moderate
          allow-licenses: >-
            0BSD,
            Apache-2.0,
            BSD-2-Clause,
            BSD-3-Clause,
            CC0-1.0,
            MIT,
            MIT-0
          comment-summary-in-pr: always
