---
name: "JSLint"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    name: Check with JSLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install JSLint
        shell: bash
        run: sudo npm install -g jslint
      - name: Run JSLint
        shell: bash
        run: jslint --browser javascripts/*.js
