---
name: "JSLint"

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:

  check:
    name: Check with JSLint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Install JSLint
      run: sudo npm install -g jslint
    - name: Run JSLint
      run: jslint --browser javascripts/*.js
